export const ETHEREUM_RPC_URL = process.env.REACT_APP_ETHEREUM_RPC_URL;
export const ETHEREUM_CHAIN_ID = Number(process.env.REACT_APP_ETHEREUM_CHAIN_ID);
export const KIRA_TOKEN_ADDRESS = process.env.REACT_APP_KIRA_TOKEN_ADDRESS;
export const NFT_MINTING_ADDRESS = process.env.REACT_APP_NFT_MINTING_ADDRESS;
export const NFT_FARM_ADDRESS = process.env.REACT_APP_NFT_FARM_ADDRESS;
export const NFT_STAKING_ADDRESS = process.env.REACT_APP_NFT_STAKING_ADDRESS;